"""計算公然侮辱 SFT 的離線任務指標並輸出可稽核報表。

本腳本只讀取 04_run_inference.py 產生的 JSONL，不載入 TAIDE 或 LoRA adapter。
因此可在訓練期間撰寫與測試，但正式 test set 報告應等模型與 checkpoint 選定後才執行。
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
import random
import sys
from typing import Any, Iterable


PROJECT_ROOT = Path(__file__).resolve().parents[2]
SFT_SRC = PROJECT_ROOT / "sft/src"
if str(SFT_SRC) not in sys.path:
    sys.path.insert(0, str(SFT_SRC))

from public_insult_sft.evaluation import (
    compute_bertscore,
    evaluate_prediction_records,
)  # noqa: E402


DEFAULT_PREDICTION_DIR = PROJECT_ROOT / "sft/outputs/predictions"
DEFAULT_EVALUATION_DIR = PROJECT_ROOT / "sft/outputs/evaluations"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate generated public-insult judgment predictions without loading the language model."
    )
    parser.add_argument(
        "--predictions",
        type=Path,
        required=True,
        help="JSONL generated by 04_run_inference.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Report directory. Defaults to sft/outputs/evaluations/<prediction-file-stem>.",
    )
    parser.add_argument(
        "--bertscore",
        action="store_true",
        help="Compute optional Chinese BERTScore. Run only after TAIDE training releases MPS memory.",
    )
    parser.add_argument(
        "--bertscore-model",
        default=None,
        help="Optional Hugging Face model passed to bert-score; omitted uses its zh default.",
    )
    parser.add_argument(
        "--bertscore-device",
        default=None,
        help="Optional bert-score device, for example mps or cpu.",
    )
    parser.add_argument("--bertscore-batch-size", type=int, default=8)
    parser.add_argument(
        "--human-review-size",
        type=int,
        default=30,
        help="Number of deterministic, class-balanced cases exported for manual legal review.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite known report files in an existing report directory; unrelated files are preserved.",
    )
    return parser.parse_args()


def resolve_project_path(path: Path) -> Path:
    return path if path.is_absolute() else PROJECT_ROOT / path


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(f"Prediction file not found: {path}")

    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as file:
        for line_number, line in enumerate(file, start=1):
            if not line.strip():
                continue
            try:
                value = json.loads(line)
            except json.JSONDecodeError as error:
                raise ValueError(
                    f"Invalid JSON at {path}:{line_number}: {error}"
                ) from error
            if not isinstance(value, dict):
                raise ValueError(
                    f"Each line must be a JSON object: {path}:{line_number}"
                )
            records.append(value)
    if not records:
        raise ValueError(f"Prediction file contains no records: {path}")
    return records


def _atomic_text_write(path: Path, text: str) -> None:
    """先寫入同目錄暫存檔再 replace，避免中斷後留下半份 JSON 報告。"""
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(text, encoding="utf-8")
    temporary.replace(path)


def write_json(path: Path, value: Any) -> None:
    _atomic_text_write(path, json.dumps(value, ensure_ascii=False, indent=2) + "\n")


def write_jsonl(path: Path, rows: Iterable[dict[str, Any]]) -> None:
    content = "".join(json.dumps(row, ensure_ascii=False) + "\n" for row in rows)
    _atomic_text_write(path, content)


def write_csv(
    path: Path, fieldnames: list[str], rows: Iterable[dict[str, Any]]
) -> None:
    temporary = path.with_name(f".{path.name}.tmp")
    with temporary.open("w", encoding="utf-8-sig", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    temporary.replace(path)


def write_confusion_matrix(path: Path, confusion: dict[str, Any]) -> None:
    """輸出任意分類層級的 confusion matrix，刑種與刑度區間共用同一格式。"""
    labels = confusion["labels"]
    rows = []
    for actual_label, counts in zip(labels, confusion["values"]):
        row: dict[str, Any] = {"actual\\predicted": actual_label}
        row.update(dict(zip(labels, counts)))
        rows.append(row)
    write_csv(path, ["actual\\predicted", *labels], rows)


def balanced_review_sample(
    case_results: list[dict[str, Any]],
    requested_size: int,
    seed: int,
) -> list[dict[str, Any]]:
    """輪流從各真實類別抽樣，避免多數類別主導人工審查。"""
    if requested_size <= 0:
        return []
    random_generator = random.Random(seed)
    groups: dict[str, list[dict[str, Any]]] = {}
    for result in case_results:
        groups.setdefault(result["actual_sentence_type"], []).append(result)
    for group in groups.values():
        random_generator.shuffle(group)

    selected: list[dict[str, Any]] = []
    labels = sorted(groups)
    while len(selected) < min(requested_size, len(case_results)):
        made_progress = False
        for label in labels:
            if groups[label] and len(selected) < requested_size:
                selected.append(groups[label].pop())
                made_progress = True
        if not made_progress:
            break
    return selected


def human_review_rows(
    sample: list[dict[str, Any]],
    prediction_records: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """加入原始案情與空白評分欄位，供法律專業人員人工覆核。"""
    records_by_case_id = {
        str(record["case_id"]): record for record in prediction_records
    }
    rows: list[dict[str, Any]] = []
    for result in sample:
        source = records_by_case_id[result["case_id"]]
        input_messages = source.get("input_messages", [])
        user_prompt = "\n\n".join(
            message.get("content", "")
            for message in input_messages
            if isinstance(message, dict) and message.get("role") == "user"
        )
        rows.append(
            {
                "case_id": result["case_id"],
                "case_facts_and_factors": user_prompt,
                "actual_sentence_type": result["actual_sentence_type"],
                "predicted_sentence_type": result["predicted_sentence_type"],
                "actual_sentence_amount_band": result["actual_sentence_amount_band"],
                "predicted_sentence_amount_band": result[
                    "predicted_sentence_amount_band"
                ],
                "reference_reason": result["reference_reason"],
                "generated_reason": result["generated_reason"],
                "factual_consistency_1_to_5": "",
                "sentencing_factor_completeness_1_to_5": "",
                "legal_reasoning_appropriateness_1_to_5": "",
                "hallucination_present_yes_no": "",
                "reviewer_notes": "",
            }
        )
    return rows


def prepare_output_directory(output_dir: Path, overwrite: bool) -> None:
    known_outputs = (
        "metrics.json",
        "case_results.jsonl",
        "confusion_matrix.csv",
        "amount_band_confusion_matrix.csv",
        "human_review.csv",
    )
    existing = [
        output_dir / filename
        for filename in known_outputs
        if (output_dir / filename).exists()
    ]
    if existing and not overwrite:
        names = ", ".join(path.name for path in existing)
        raise FileExistsError(
            f"Evaluation outputs already exist ({names}); use --overwrite to replace them."
        )
    output_dir.mkdir(parents=True, exist_ok=True)


def main() -> None:
    args = parse_args()
    if args.bertscore_batch_size <= 0:
        raise ValueError("--bertscore-batch-size must be greater than zero.")
    if args.human_review_size < 0:
        raise ValueError("--human-review-size cannot be negative.")

    prediction_path = resolve_project_path(args.predictions)
    output_dir = (
        resolve_project_path(args.output_dir)
        if args.output_dir is not None
        else DEFAULT_EVALUATION_DIR / prediction_path.stem
    )
    prepare_output_directory(output_dir, args.overwrite)

    prediction_records = load_jsonl(prediction_path)
    metrics, case_results = evaluate_prediction_records(prediction_records)

    if args.bertscore:
        bertscore_metrics, per_case_f1 = compute_bertscore(
            case_results,
            model_type=args.bertscore_model,
            batch_size=args.bertscore_batch_size,
            device=args.bertscore_device,
        )
        metrics["sentencing_reason"]["bertscore"] = bertscore_metrics
        for result, bertscore_f1 in zip(case_results, per_case_f1):
            result["bertscore_f1"] = bertscore_f1

    write_json(output_dir / "metrics.json", metrics)
    write_jsonl(output_dir / "case_results.jsonl", case_results)
    write_confusion_matrix(
        output_dir / "confusion_matrix.csv", metrics["confusion_matrix"]
    )
    if "amount_band_confusion_matrix" in metrics:
        write_confusion_matrix(
            output_dir / "amount_band_confusion_matrix.csv",
            metrics["amount_band_confusion_matrix"],
        )

    review_sample = balanced_review_sample(
        case_results, args.human_review_size, args.seed
    )
    review_rows = human_review_rows(review_sample, prediction_records)
    write_csv(
        output_dir / "human_review.csv",
        [
            "case_id",
            "case_facts_and_factors",
            "actual_sentence_type",
            "predicted_sentence_type",
            "actual_sentence_amount_band",
            "predicted_sentence_amount_band",
            "reference_reason",
            "generated_reason",
            "factual_consistency_1_to_5",
            "sentencing_factor_completeness_1_to_5",
            "legal_reasoning_appropriateness_1_to_5",
            "hallucination_present_yes_no",
            "reviewer_notes",
        ],
        review_rows,
    )

    print(f"Evaluated cases: {metrics['dataset']['case_count']}")
    print(f"Strict JSON valid rate: {metrics['format']['strict_json_valid_rate']:.4f}")
    print(f"Schema compliance rate: {metrics['format']['schema_compliance_rate']:.4f}")
    print(f"Sentence type accuracy: {metrics['classification']['accuracy']:.4f}")
    print(f"Sentence type Macro-F1: {metrics['classification']['macro_f1']:.4f}")
    if metrics["sentence_amount"]["mode"] == "band":
        print(
            f"Amount band accuracy: {metrics['sentence_amount']['classification']['accuracy']:.4f}"
        )
        print(
            f"Amount band Macro-F1: {metrics['sentence_amount']['classification']['macro_f1']:.4f}"
        )
    print(f"ROUGE-L F1: {metrics['sentencing_reason']['rouge_l_f1']:.4f}")
    print(f"Joint success rate: {metrics['end_to_end']['joint_success_rate']:.4f}")
    print(f"Reports saved to: {output_dir}")


if __name__ == "__main__":
    main()
